import { i } from "@instantdb/admin";

import type { WorkroomCloudSnapshot } from "./shared/workroom-snapshot";

const _schema = i.schema({
  entities: {
    users: i.entity({
      openId: i.string().unique().indexed(),
      name: i.string().optional(),
      email: i.string().optional(),
      loginMethod: i.string().optional(),
      role: i.string(),
      createdAt: i.date(),
      updatedAt: i.date(),
      lastSignedIn: i.date(),
    }),
    pushDevices: i.entity({
      installationId: i.string().unique().indexed(),
      userId: i.string().indexed(),
      expoPushToken: i.string(),
      approvalEnabled: i.boolean(),
      completionEnabled: i.boolean(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    userNotificationPreferences: i.entity({
      userId: i.string().unique().indexed(),
      approvalEnabled: i.boolean(),
      completionEnabled: i.boolean(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    microsoftConnections: i.entity({
      accountId: i.string().unique().indexed(),
      userId: i.string().indexed(),
      microsoftUserId: i.string(),
      displayName: i.string().optional(),
      email: i.string().optional(),
      encryptedAccessToken: i.string(),
      encryptedRefreshToken: i.string(),
      expiresAt: i.date().indexed(),
      scopes: i.string(),
      status: i.string().indexed(),
      isPrimary: i.boolean().optional(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    microsoftOAuthStates: i.entity({
      state: i.string().unique().indexed(),
      userId: i.string().indexed(),
      codeVerifier: i.string(),
      returnTo: i.string(),
      expiresAt: i.date().indexed(),
      createdAt: i.date(),
    }),
    excelPendingActions: i.entity({
      actionId: i.string().unique().indexed(),
      userId: i.string().indexed(),
      botClientId: i.string(),
      taskClientId: i.string().indexed(),
      toolName: i.string(),
      arguments: i.json<Record<string, unknown>>(),
      summary: i.string(),
      state: i.string().indexed(),
      result: i.json<unknown>().optional(),
      expiresAt: i.date().indexed(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    excelActionClaims: i.entity({
      actionId: i.string().unique().indexed(),
      userId: i.string().indexed(),
      createdAt: i.date(),
    }),
    workroomSnapshots: i.entity({
      userId: i.string().unique().indexed(),
      syncVersion: i.string().indexed(),
      snapshot: i.json<WorkroomCloudSnapshot>(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    workroomBots: i.entity({
      recordKey: i.string().unique().indexed(),
      userId: i.string().indexed(),
      syncVersion: i.string().indexed(),
      clientId: i.string().indexed(),
      name: i.string(),
      role: i.string(),
      status: i.string(),
      color: i.string(),
      icon: i.string(),
      payload: i.json<Record<string, unknown>>(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    workroomTasks: i.entity({
      recordKey: i.string().unique().indexed(),
      userId: i.string().indexed(),
      syncVersion: i.string().indexed(),
      clientId: i.string().indexed(),
      botClientId: i.string().indexed(),
      title: i.string(),
      status: i.string(),
      risk: i.string(),
      payload: i.json<Record<string, unknown>>(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    workroomFiles: i.entity({
      recordKey: i.string().unique().indexed(),
      userId: i.string().indexed(),
      syncVersion: i.string().indexed(),
      clientId: i.string().indexed(),
      name: i.string(),
      owner: i.string(),
      scope: i.string(),
      payload: i.json<Record<string, unknown>>(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    rookNodes: i.entity({
      nodeId: i.string().unique().indexed(),
      userId: i.string().indexed(),
      name: i.string(),
      secretHash: i.string(),
      status: i.string().indexed(),
      version: i.string(),
      lastSeenAt: i.date(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    pairingTokens: i.entity({
      tokenHash: i.string().unique().indexed(),
      userId: i.string().indexed(),
      usedByNodeId: i.string().optional(),
      expiresAt: i.date().indexed(),
      createdAt: i.date(),
    }),
    desktopPairingRequests: i.entity({
      requestId: i.string().unique().indexed(),
      codeHash: i.string().optional().indexed(),
      userId: i.string().optional().indexed(),
      name: i.string(),
      version: i.string(),
      attempts: i.number(),
      state: i.string().indexed(),
      usedByNodeId: i.string().optional(),
      expiresAt: i.date().indexed(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    desktopPairingClaims: i.entity({
      requestId: i.string().unique().indexed(),
      nodeId: i.string().unique().indexed(),
      userId: i.string().indexed(),
      createdAt: i.date(),
    }),
    nodeCommands: i.entity({
      commandId: i.string().unique().indexed(),
      userId: i.string().indexed(),
      nodeId: i.string().indexed(),
      state: i.string().indexed(),
      summary: i.string(),
      capability: i.string(),
      envelope: i.json<Record<string, unknown>>(),
      approval: i.json<Record<string, unknown>>().optional(),
      result: i.json<unknown>().optional(),
      expiresAt: i.date().indexed(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
  },
  links: {},
});

type _AppSchema = typeof _schema;
export interface AppSchema extends _AppSchema {}

const schema: AppSchema = _schema;
export default schema;
